#!/usr/bin/env zsh

DOTFILES=$(dirname "$0")

CURRENT_DIRECTORY=$(pwd)

pushd $DOTFILES

for folder in $(ls -dm */ | tr '\,\/' ' ') 
do
    echo "Uninstalling '$folder'..."
    stow -D $folder
done

if [ "$CURRENT_DIRECTORY" != "$DOTFILES" ]; then
    popd
fi
